
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 12 14:37:46 EDT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A4Symbol {
  /* terminals */
  public static final int READ = 5;
  public static final int ELSE = 8;
  public static final int PLUS = 17;
  public static final int INT = 24;
  public static final int EQUAL = 22;
  public static final int NOTEQUAL = 21;
  public static final int END = 9;
  public static final int RETURN = 4;
  public static final int IF = 7;
  public static final int WRITE = 3;
  public static final int ID = 11;
  public static final int SCOLON = 15;
  public static final int BEGIN = 10;
  public static final int STRING = 26;
  public static final int COMMA = 16;
  public static final int QUOTATIONS = 2;
  public static final int MULT = 20;
  public static final int EOF = 0;
  public static final int NUMBER = 12;
  public static final int DIVIDE = 19;
  public static final int LEBRAC = 13;
  public static final int MAIN = 6;
  public static final int COLEQUAL = 23;
  public static final int MINUS = 18;
  public static final int error = 1;
  public static final int RIGBRAC = 14;
  public static final int REAL = 25;
}

